# Generated by Django 3.1.7 on 2021-04-05 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submitted_translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
